// 反向映射：global CSS变量 -> antToken
export const globalToAntTokenMappings = {
  // 基础颜色映射
  '--color-blue-1': ['blue-1', 'blue1'],
  '--color-blue-2': ['blue-2', 'blue2'],
  '--color-blue-3': ['blue-3', 'blue3'],
  '--color-blue-4': ['blue-4', 'blue4'],
  '--color-blue-5': ['blue-5', 'blue5'],
  '--color-blue-6': ['blue-6', 'blue6'],
  '--color-blue-7': ['blue-7', 'blue7'],
  '--color-blue-8': ['blue-8', 'blue8', 'colorPrimaryTextHover'],
  '--color-blue-9': ['blue-9', 'blue9', 'colorInfo', 'colorInfoActive'],
  '--color-blue-10': ['blue-10', 'blue10', 'colorInfoHover', 'colorLinkActive'],
  '--color-blue-a2': ['colorInfoBgHover'],
  '--color-blue-a5': ['colorInfoBorder'],
  '--color-blue-a6': ['colorInfoBorderHover'],
  '--color-blue-a10': ['colorInfoTextHover', 'colorLinkHover'],
  '--color-blue-a11': ['colorLink', 'colorInfoText', 'colorInfoTextActive'],

  '--color-purple-1': ['purple-1', 'purple1'],
  '--color-purple-2': ['purple-2', 'purple2'],
  '--color-purple-3': ['purple-3', 'purple3'],
  '--color-purple-4': ['purple-4', 'purple4'],
  '--color-purple-5': ['purple-5', 'purple5'],
  '--color-purple-6': ['purple-6', 'purple6'],
  '--color-purple-7': ['purple-7', 'purple7'],
  '--color-purple-8': ['purple-8', 'purple8'],
  '--color-purple-9': ['purple-9', 'purple9'],
  '--color-purple-10': ['purple-10', 'purple10'],

  '--color-cyan-1': ['cyan-1', 'cyan1'],
  '--color-cyan-2': ['cyan-2', 'cyan2'],
  '--color-cyan-3': ['cyan-3', 'cyan3'],
  '--color-cyan-4': ['cyan-4', 'cyan4'],
  '--color-cyan-5': ['cyan-5', 'cyan5'],
  '--color-cyan-6': ['cyan-6', 'cyan6'],
  '--color-cyan-7': ['cyan-7', 'cyan7'],
  '--color-cyan-8': ['cyan-8', 'cyan8'],
  '--color-cyan-9': ['cyan-9', 'cyan9'],
  '--color-cyan-10': ['cyan-10', 'cyan10'],

  '--color-green-1': ['green-1', 'green1'],
  '--color-green-2': ['green-2', 'green2', 'colorSuccessBg'],
  '--color-green-3': ['green-3', 'green3'],
  '--color-green-4': ['green-4', 'green4'],
  '--color-green-5': ['green-5', 'green5'],
  '--color-green-6': ['green-6', 'green6'],
  '--color-green-7': ['green-7', 'green7'],
  '--color-green-8': ['green-8', 'green8'],
  '--color-green-9': [
    'green-9',
    'green9',
    'colorSuccess',
    'colorSuccessActive',
  ],
  '--color-green-10': ['green-10', 'green10', 'colorSuccessHover'],
  '--color-green-a2': ['colorSuccessBgHover'],
  '--color-green-a5': ['colorSuccessBorder'],
  '--color-green-a6': ['colorSuccessBorderHover'],
  '--color-green-a10': ['colorSuccessTextHover'],
  '--color-green-a11': ['colorSuccessText', 'colorSuccessTextActive'],

  '--color-magenta-1': ['magenta-1', 'magenta1'],
  '--color-magenta-2': ['magenta-2', 'magenta2'],
  '--color-magenta-3': ['magenta-3', 'magenta3'],
  '--color-magenta-4': ['magenta-4', 'magenta4'],
  '--color-magenta-5': ['magenta-5', 'magenta5'],
  '--color-magenta-6': ['magenta-6', 'magenta6'],
  '--color-magenta-7': ['magenta-7', 'magenta7'],
  '--color-magenta-8': ['magenta-8', 'magenta8'],
  '--color-magenta-9': ['magenta-9', 'magenta9'],
  '--color-magenta-10': ['magenta-10', 'magenta10'],

  '--color-pink-1': ['pink-1', 'pink1'],
  '--color-pink-2': ['pink-2', 'pink2'],
  '--color-pink-3': ['pink-3', 'pink3'],
  '--color-pink-4': ['pink-4', 'pink4'],
  '--color-pink-5': ['pink-5', 'pink5'],
  '--color-pink-6': ['pink-6', 'pink6'],
  '--color-pink-7': ['pink-7', 'pink7'],
  '--color-pink-8': ['pink-8', 'pink8'],
  '--color-pink-9': ['pink-9', 'pink9'],
  '--color-pink-10': ['pink-10', 'pink10'],

  '--color-red-1': ['red-1', 'red1'],
  '--color-red-2': ['red-2', 'red2', 'colorErrorBg'],
  '--color-red-3': ['red-3', 'red3'],
  '--color-red-4': ['red-4', 'red4'],
  '--color-red-5': ['red-5', 'red5'],
  '--color-red-6': ['red-6', 'red6'],
  '--color-red-7': ['red-7', 'red7'],
  '--color-red-8': ['red-8', 'red8'],
  '--color-red-9': ['red-9', 'red9', 'colorError', 'colorErrorActive'],
  '--color-red-10': ['red-10', 'red10', 'colorErrorHover'],
  '--color-red-a2': ['colorErrorBgHover'],
  '--color-red-a3': ['colorErrorBgActive'],
  '--color-red-a4': ['colorErrorBgFilledHover'],
  '--color-red-a5': ['colorErrorBorder', 'colorErrorOutline'],
  '--color-red-a6': ['colorErrorBorderHover'],
  '--color-red-a10': ['colorErrorTextHover'],
  '--color-red-a11': ['colorErrorText', 'colorErrorTextActive'],

  '--color-orange-1': ['orange-1', 'orange1'],
  '--color-orange-2': ['orange-2', 'orange2'],
  '--color-orange-3': ['orange-3', 'orange3'],
  '--color-orange-4': ['orange-4', 'orange4'],
  '--color-orange-5': ['orange-5', 'orange5'],
  '--color-orange-6': ['orange-6', 'orange6'],
  '--color-orange-7': ['orange-7', 'orange7'],
  '--color-orange-8': ['orange-8', 'orange8'],
  '--color-orange-9': ['orange-9', 'orange9'],
  '--color-orange-10': ['orange-10', 'orange10'],

  '--color-yellow-1': ['yellow-1', 'yellow1'],
  '--color-yellow-2': ['yellow-2', 'yellow2', 'colorWarningBg'],
  '--color-yellow-3': ['yellow-3', 'yellow3'],
  '--color-yellow-4': ['yellow-4', 'yellow4'],
  '--color-yellow-5': ['yellow-5', 'yellow5'],
  '--color-yellow-6': ['yellow-6', 'yellow6'],
  '--color-yellow-7': ['yellow-7', 'yellow7'],
  '--color-yellow-8': ['yellow-8', 'yellow8'],
  '--color-yellow-9': [
    'yellow-9',
    'yellow9',
    'colorWarning',
    'colorWarningActive',
    'colorWarningTextHover',
  ],
  '--color-yellow-10': [
    'yellow-10',
    'yellow10',
    'colorWarningHover',
    'colorWarningTextActive',
  ],
  '--color-yellow-a3': ['colorWarningBgHover'],
  '--color-yellow-a5': ['colorWarningBorder', 'colorWarningOutline'],
  '--color-yellow-a6': ['colorWarningBorderHover'],
  '--color-yellow-a11': ['colorWarningText'],

  '--color-volcano-1': ['volcano-1', 'volcano1'],
  '--color-volcano-2': ['volcano-2', 'volcano2'],
  '--color-volcano-3': ['volcano-3', 'volcano3'],
  '--color-volcano-4': ['volcano-4', 'volcano4'],
  '--color-volcano-5': ['volcano-5', 'volcano5'],
  '--color-volcano-6': ['volcano-6', 'volcano6'],
  '--color-volcano-7': ['volcano-7', 'volcano7'],
  '--color-volcano-8': ['volcano-8', 'volcano8'],
  '--color-volcano-9': ['volcano-9', 'volcano9'],
  '--color-volcano-10': ['volcano-10', 'volcano10'],

  '--color-geekblue-1': ['geekblue-1', 'geekblue1'],
  '--color-geekblue-2': ['geekblue-2', 'geekblue2'],
  '--color-geekblue-3': ['geekblue-3', 'geekblue3'],
  '--color-geekblue-4': ['geekblue-4', 'geekblue4'],
  '--color-geekblue-5': ['geekblue-5', 'geekblue5'],
  '--color-geekblue-6': ['geekblue-6', 'geekblue6'],
  '--color-geekblue-7': ['geekblue-7', 'geekblue7'],
  '--color-geekblue-8': ['geekblue-8', 'geekblue8'],
  '--color-geekblue-9': ['geekblue-9', 'geekblue9'],
  '--color-geekblue-10': ['geekblue-10', 'geekblue10'],

  '--color-gold-1': ['gold-1', 'gold1'],
  '--color-gold-2': ['gold-2', 'gold2'],
  '--color-gold-3': ['gold-3', 'gold3'],
  '--color-gold-4': ['gold-4', 'gold4'],
  '--color-gold-5': ['gold-5', 'gold5'],
  '--color-gold-6': ['gold-6', 'gold6'],
  '--color-gold-7': ['gold-7', 'gold7'],
  '--color-gold-8': ['gold-8', 'gold8'],
  '--color-gold-9': ['gold-9', 'gold9'],
  '--color-gold-10': ['gold-10', 'gold10'],

  '--color-lime-1': ['lime-1', 'lime1'],
  '--color-lime-2': ['lime-2', 'lime2'],
  '--color-lime-3': ['lime-3', 'lime3'],
  '--color-lime-4': ['lime-4', 'lime4'],
  '--color-lime-5': ['lime-5', 'lime5'],
  '--color-lime-6': ['lime-6', 'lime6'],
  '--color-lime-7': ['lime-7', 'lime7'],
  '--color-lime-8': ['lime-8', 'lime8'],
  '--color-lime-9': ['lime-9', 'lime9'],
  '--color-lime-10': ['lime-10', 'lime10'],

  // 主色调映射
  '--color-primary-2': ['colorPrimaryBg'],
  '--color-primary-3': ['controlItemBgActive'],
  '--color-primary-4': ['controlItemBgActiveHover'],
  '--color-primary-9': ['colorPrimary', 'colorPrimaryActive'],
  '--color-primary-10': ['colorPrimaryHover'],
  '--color-primary-a3': ['colorPrimaryBgHover', 'controlOutline'],
  '--color-primary-a5': ['colorPrimaryBorder'],
  '--color-primary-a6': ['colorPrimaryBorderHover'],
  '--color-primary-a10': ['colorPrimaryTextActive'],
  '--color-primary-a11': ['colorPrimaryText'],

  // 中性色/灰色映射
  '--color-gray-2': ['colorBgLayout'],
  '--color-gray-12': ['colorTextBase'],
  '--color-gray-a1': ['colorFillQuaternary'],
  '--color-gray-a2': [
    'colorFillTertiary',
    'colorFillAlter',
    'colorBgContainerDisabled',
  ],
  '--color-gray-a3': [
    'colorBorderSecondary',
    'colorFillSecondary',
    'colorFillContent',
    'colorBgTextHover',
    'controlItemBgHover',
  ],
  '--color-gray-a5': [
    'colorBorder',
    'colorFill',
    'colorBgTextActive',
    'colorSplit',
    'colorFillContentHover',
    'controlItemBgActiveDisabled',
  ],
  '--color-gray-a8': [
    'colorTextQuaternary',
    'colorTextDisabled',
    'colorTextPlaceholder',
  ],
  '--color-gray-a9': ['colorTextTertiary', 'colorIcon', 'colorTextDescription'],
  '--color-gray-a11': ['colorTextSecondary', 'colorTextLabel', 'colorBgMask'],
  '--color-gray-a12': [
    'colorText',
    'colorTextHeading',
    'colorIconHover',
    'colorBgSpotlight',
  ],

  // 基础色值映射
  '--color-white': [
    'colorWhite',
    'colorBgBase',
    'colorBgContainer',
    'colorBgElevated',
  ],
  '--color-black': ['colorTextBase'],

  // 补充基础颜色名称映射
  '--color-blue': ['blue'],
  '--color-purple': ['purple'],
  '--color-cyan': ['cyan'],
  '--color-green': ['green'],
  '--color-magenta': ['magenta'],
  '--color-pink': ['pink'],
  '--color-red': ['red'],
  '--color-orange': ['orange'],
  '--color-yellow': ['yellow'],
  '--color-volcano': ['volcano'],
  '--color-geekblue': ['geekblue'],
  '--color-gold': ['gold'],
  '--color-lime': ['lime'],

  // 字体相关映射
  '--font-family': ['fontFamily'],
  '--font-family-code': ['fontFamilyCode'],
  '--font-size': ['fontSize'],
  '--font-size-sm': ['fontSizeSM'],
  '--font-size-lg': ['fontSizeLG'],
  '--font-size-xl': ['fontSizeXL'],
  '--font-size-heading1': ['fontSizeHeading1'],
  '--font-size-heading2': ['fontSizeHeading2'],
  '--font-size-heading3': ['fontSizeHeading3'],
  '--font-size-heading4': ['fontSizeHeading4'],
  '--font-size-heading5': ['fontSizeHeading5'],
  '--font-size-icon': ['fontSizeIcon'],
  '--font-weight-strong': ['fontWeightStrong'],
  '--font-height': ['fontHeight'],
  '--font-height-lg': ['fontHeightLG'],
  '--font-height-sm': ['fontHeightSM'],

  // 行高映射
  '--line-height': ['lineHeight'],
  '--line-height-lg': ['lineHeightLG'],
  '--line-height-sm': ['lineHeightSM'],
  '--line-height-heading1': ['lineHeightHeading1'],
  '--line-height-heading2': ['lineHeightHeading2'],
  '--line-height-heading3': ['lineHeightHeading3'],
  '--line-height-heading4': ['lineHeightHeading4'],
  '--line-height-heading5': ['lineHeightHeading5'],

  // 线条相关映射
  '--line-width': ['lineWidth'],
  '--line-width-bold': ['lineWidthBold'],
  '--line-width-focus': ['lineWidthFocus'],
  '--line-type': ['lineType'],

  // 动效映射
  '--motion-unit': ['motionUnit'],
  '--motion-base': ['motionBase'],
  '--motion': ['motion'],
  '--motion-ease-out-circ': ['motionEaseOutCirc'],
  '--motion-ease-in-out-circ': ['motionEaseInOutCirc'],
  '--motion-ease-out': ['motionEaseOut'],
  '--motion-ease-in-out': ['motionEaseInOut'],
  '--motion-ease-out-back': ['motionEaseOutBack'],
  '--motion-ease-in-back': ['motionEaseInBack'],
  '--motion-ease-in-quint': ['motionEaseInQuint'],
  '--motion-ease-out-quint': ['motionEaseOutQuint'],
  '--motion-duration-fast': ['motionDurationFast'],
  '--motion-duration-mid': ['motionDurationMid'],
  '--motion-duration-slow': ['motionDurationSlow'],

  // 边框圆角映射
  '--radius-base': ['borderRadius', 'borderRadiusOuter'],
  '--radius-xs': ['borderRadiusXS'],
  '--radius-sm': ['borderRadiusSM'],
  '--radius-lg': ['borderRadiusLG'],

  // 尺寸映射
  '--padding-unit': ['sizeUnit', 'sizeStep'],
  '--size-popup-arrow': ['sizePopupArrow'],
  '--padding-1x': ['sizeXXS', 'paddingXXS'],
  '--padding-2x': ['sizeXS', 'paddingXS', 'controlPaddingHorizontalSM'],
  '--padding-3x': ['sizeSM', 'paddingSM', 'controlPaddingHorizontal'],
  '--padding-4x': ['size', 'sizeMS', 'padding'],
  '--padding-5x': ['sizeMD', 'paddingMD'],
  '--padding-6x': ['sizeLG', 'paddingLG'],
  '--padding-8x': ['sizeXL', 'paddingXL'],
  '--padding-12x': ['sizeXXL'],

  // 内边距映射
  '--padding-content-horizontal': ['paddingContentHorizontal'],
  '--padding-content-vertical': ['paddingContentVertical'],
  '--padding-content-horizontal-sm': ['paddingContentHorizontalSM'],
  '--padding-content-vertical-sm': ['paddingContentVerticalSM'],
  '--padding-content-horizontal-lg': ['paddingContentHorizontalLG'],
  '--padding-content-vertical-lg': ['paddingContentVerticalLG'],

  // 外边距映射
  '--margin-1x': ['marginXXS'],
  '--margin-2x': ['marginXS'],
  '--margin-3x': ['marginSM'],
  '--margin-4x': ['margin', 'marginMD'],
  '--margin-6x': ['marginLG'],
  '--margin-8x': ['marginXL'],
  '--margin-12x': ['marginXXL'],

  // 控件高度映射
  '-height-control-base': ['controlHeight'],
  '--height-control-xs': ['controlHeightXS'],
  '--height-control-sm': ['controlHeightSM'],
  '--height-control-lg': ['controlHeightLG'],

  // 阴影映射
  '--shadow-border-base': ['boxShadow'],
  '--shadow-hard-sm': ['boxShadowSecondary'],
  '--shadow-hard-xs': ['boxShadowTertiary'],
  '--shadow-card-base': ['boxShadowCard'],
  '--shadow-popover-base': ['boxShadowPopoverArrow'],
  '--shadow-modal-base': ['boxShadowDrawerUp', 'boxShadowDrawerDown'],

  '--box-shadow-drawer-right': ['boxShadowDrawerRight'],
  '--box-shadow-drawer-left': ['boxShadowDrawerLeft'],
  '--box-shadow-tabs-overflow-left': ['boxShadowTabsOverflowLeft'],
  '--box-shadow-tabs-overflow-right': ['boxShadowTabsOverflowRight'],
  '--box-shadow-tabs-overflow-top': ['boxShadowTabsOverflowTop'],
  '--box-shadow-tabs-overflow-bottom': ['boxShadowTabsOverflowBottom'],

  // 补充未映射的 antToken
  '--color-border-bg': ['colorBorderBg'],
  '--color-text-light-solid': ['colorTextLightSolid'],
  // 语义化颜色补充
  '--color-success-hover': ['colorSuccessHover'],
  '--color-info-hover': ['colorInfoHover'],
};
